# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PreviewAnimationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_animation_view(object):
    def setupUi(self, animation_view):
        animation_view.setObjectName("animation_view")
        animation_view.resize(578, 542)
        self.verticalLayout = QtWidgets.QVBoxLayout(animation_view)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(animation_view)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.animation_info_label = QtWidgets.QLabel(self.frame)
        self.animation_info_label.setObjectName("animation_info_label")
        self.horizontalLayout.addWidget(self.animation_info_label)
        self.pose_combobox = QtWidgets.QComboBox(self.frame)
        self.pose_combobox.setObjectName("pose_combobox")
        self.horizontalLayout.addWidget(self.pose_combobox)
        self.framerate_adjust = QtWidgets.QSpinBox(self.frame)
        self.framerate_adjust.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.framerate_adjust.setMinimum(1)
        self.framerate_adjust.setMaximum(140)
        self.framerate_adjust.setProperty("value", 24)
        self.framerate_adjust.setObjectName("framerate_adjust")
        self.horizontalLayout.addWidget(self.framerate_adjust)
        self.play_anim_button = QtWidgets.QPushButton(self.frame)
        self.play_anim_button.setObjectName("play_anim_button")
        self.horizontalLayout.addWidget(self.play_anim_button)
        self.verticalLayout.addWidget(self.frame)
        self.animation_display_area = QtWidgets.QLabel(animation_view)
        self.animation_display_area.setMaximumSize(QtCore.QSize(2000, 2000))
        self.animation_display_area.setAlignment(QtCore.Qt.AlignCenter)
        self.animation_display_area.setObjectName("animation_display_area")
        self.verticalLayout.addWidget(self.animation_display_area)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(animation_view)
        QtCore.QMetaObject.connectSlotsByName(animation_view)

    def retranslateUi(self, animation_view):
        _translate = QtCore.QCoreApplication.translate
        animation_view.setWindowTitle(_translate("animation_view", "Animation Preview"))
        self.animation_info_label.setText(_translate("animation_view", "Animation Name to be played:"))
        self.framerate_adjust.setSuffix(_translate("animation_view", "fps"))
        self.play_anim_button.setText(_translate("animation_view", "Play Animation"))
        self.animation_display_area.setText(_translate("animation_view", "--PIXMAP GOES HERE--"))
