# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrameOrderWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrameOrderScreen(object):
    def setupUi(self, FrameOrderScreen):
        FrameOrderScreen.setObjectName("FrameOrderScreen")
        FrameOrderScreen.resize(851, 628)
        self.verticalLayout = QtWidgets.QVBoxLayout(FrameOrderScreen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(FrameOrderScreen)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pose_name_combo_box = QtWidgets.QComboBox(self.frame)
        self.pose_name_combo_box.setObjectName("pose_name_combo_box")
        self.horizontalLayout.addWidget(self.pose_name_combo_box)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea = QtWidgets.QScrollArea(FrameOrderScreen)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.frame_addition_widget = QtWidgets.QWidget()
        self.frame_addition_widget.setGeometry(QtCore.QRect(0, 0, 827, 551))
        self.frame_addition_widget.setObjectName("frame_addition_widget")
        self.scrollArea.setWidget(self.frame_addition_widget)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(FrameOrderScreen)
        QtCore.QMetaObject.connectSlotsByName(FrameOrderScreen)

    def retranslateUi(self, FrameOrderScreen):
        _translate = QtCore.QCoreApplication.translate
        FrameOrderScreen.setWindowTitle(_translate("FrameOrderScreen", "Change Ordering of Frames"))
        self.label.setText(_translate("FrameOrderScreen", "Select Pose Name"))
